name: Build Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build and push first image
        uses: docker/build-push-action@v3
        with:
          context: ./first-folder
          file: ./first-folder/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image-one:latest


      - name: Build and push second image
        uses: docker/build-push-action@v3
        with:
          context: ./second-folder
          file: ./second-folder/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-image-two:latest
